In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn import metrics
import matplotlib
import matplotlib.pyplot as plt

In [2]:
#讀取資料 將編碼設成utf-8  以,為分隔 資料型態為float
data = np.genfromtxt(open("train.csv", encoding = "utf8"), delimiter = ",", dtype = np.str)

In [3]:
#印出資料以觀察
print(data)

[['\ufeffid' '花萼長度' '花萼寬度' '花瓣長度' '花瓣寬度' '屬種' 'type']
 ['1' '5.4' '3.7' '1.5' '0.2' 'Iris-setosa' '1']
 ['2' '4.8' '3.4' '1.6' '0.2' 'Iris-setosa' '1']
 ['3' '4.8' '3' '1.4' '0.1' 'Iris-setosa' '1']
 ['4' '4.3' '3' '1.1' '0.1' 'Iris-setosa' '1']
 ['5' '5.8' '4' '1.2' '0.2' 'Iris-setosa' '1']
 ['6' '5.7' '4.4' '1.5' '0.4' 'Iris-setosa' '1']
 ['7' '5.4' '3.9' '1.3' '0.4' 'Iris-setosa' '1']
 ['8' '5.1' '3.5' '1.4' '0.3' 'Iris-setosa' '1']
 ['9' '5.7' '3.8' '1.7' '0.3' 'Iris-setosa' '1']
 ['10' '5.1' '3.8' '1.5' '0.3' 'Iris-setosa' '1']
 ['11' '5.4' '3.4' '1.7' '0.2' 'Iris-setosa' '1']
 ['12' '5.1' '3.7' '1.5' '0.4' 'Iris-setosa' '1']
 ['13' '4.6' '3.6' '1' '0.2' 'Iris-setosa' '1']
 ['14' '5.1' '3.3' '1.7' '0.5' 'Iris-setosa' '1']
 ['15' '4.8' '3.4' '1.9' '0.2' 'Iris-setosa' '1']
 ['16' '5' '3' '1.6' '0.2' 'Iris-setosa' '1']
 ['17' '5' '3.4' '1.6' '0.4' 'Iris-setosa' '1']
 ['18' '5.2' '3.5' '1.5' '0.2' 'Iris-setosa' '1']
 ['19' '5.2' '3.4' '1.4' '0.2' 'Iris-setosa' '1']
 ['20' '4.7' '3.2' 

In [4]:
#讀取trainData 將編碼設成utf-8  以,為分隔 略過第1列資料 讀取第1,2,3,4行資料 資料型態為float
trainData = np.genfromtxt(open("train.csv", encoding = "utf8"), delimiter = ",",skip_header = 1, usecols = (1, 2, 3, 4)).astype(np.float)

In [5]:
#讀取trainLabel 將編碼設成utf-8  以,為分隔 略過第1列資料 讀取第6行資料 資料型態為float
trainLabel = np.genfromtxt(open("train.csv", encoding = "utf8"), delimiter = ",",skip_header = 1, usecols = (6)).astype(np.float)

In [6]:
#讀取testData 將編碼設成utf-8  以,為分隔 略過第1列資料 讀取第1,2,3,4行資料 資料型態為float
testData = np.genfromtxt(open("test.csv", encoding = "utf8"), delimiter = ",",skip_header = 1, usecols = (1, 2, 3, 4)).astype(np.float)

In [7]:
#將缺失資料補0
trainData[np.isnan(trainData)] = 0
print(trainData)

[[5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.

In [8]:
#使用SVC作為模型並將trainData丟入做訓練
model = SVC()
model.fit(trainData, trainLabel)
prediction = model.predict(testData).astype(np.int)
print("accuracy:", model.score(trainData, trainLabel))

accuracy: 0.975609756097561


In [9]:
#印出confusion_matrix
print(metrics.confusion_matrix(trainLabel, model.predict(trainData)))

[[40  0  0  0]
 [ 0 38  2  0]
 [ 0  0 40  0]
 [ 0  0  1  2]]


In [10]:
#印出預測結果
index = list(range(1, len(prediction) + 1))
answer = dict(zip(index, prediction))
print("id type")
for i in index:
    print("%2d   "%i, answer[i])

id type
 1    1
 2    1
 3    1
 4    1
 5    1
 6    1
 7    1
 8    1
 9    1
10    1
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    3
22    3
23    3
24    3
25    3
26    3
27    2
28    3
29    3
30    3


In [11]:
#將結果寫入csv
np.savetxt("submission.csv", np.column_stack([index, prediction]), fmt = "%s", header = "id,type", delimiter=",", comments = "")